2024-10-24 21:58:39.776445: An error occurred while scraping reaper: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:12:17.634950: An error occurred while scraping banshee: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:13:32.765123: An error occurred while scraping banshee: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:14:47.894265: An error occurred while scraping banshee: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:16:03.017340: An error occurred while scraping banshee: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:17:18.156876: An error occurred while scraping banshee: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:18:20.579648: An error occurred while scraping hellbat: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:20:27.502928: An error occurred while scraping disruptor: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:21:42.640192: An error occurred while scraping disruptor: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:22:57.765308: An error occurred while scraping disruptor: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:24:25.243647: An error occurred while scraping zealot: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-24 22:25:40.376993: An error occurred while scraping zealot: HTTPSConnectionPool(host='api.firecrawl.dev', port=443): Max retries exceeded with url: /v0/scrape (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
